{{ if eq (toString .Values.vault_path) "nil" }}
{{ if eq .Values.receiverType "opsgenie" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
type: Opaque
data:
  opsgenie_apikey: {{ .Values.opsgenie.apikey | b64enc }}
{{ end }}
{{ if eq .Values.receiverType "slack" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
type: Opaque
data:
  slack_webhook: {{ .Values.slack.webhook | b64enc }}
{{ end }}
{{ end }}
{{ if ne (toString .Values.vault_path) "nil" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}
  dataFrom: 
  - extract: 
      key: {{ .Values.vault_path }}
{{ end }}